"""Regenerate docs/DATA_ISSUES_APPENDIX.md straight from the database.

The narrative report (docs/DATA_ISSUES.md) is written by hand; this appendix is
the machine-generated evidence behind it, so the numbers in the report can never
drift from the pipeline.

    python scripts/generate_issue_report.py
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "consultbae.db"
OUT = ROOT / "docs" / "DATA_ISSUES_APPENDIX.md"


def main() -> None:
    if not DB.exists():
        raise SystemExit("run `python -m src.pipeline` first")
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    L: list[str] = []
    add = L.append

    add("# Data issues — generated appendix\n")
    add("Generated by `scripts/generate_issue_report.py` from the `data_issue` table.")
    add("Do not edit by hand; the narrative report is `DATA_ISSUES.md`.\n")

    total, codes = conn.execute("SELECT COUNT(*), COUNT(DISTINCT issue_code) FROM data_issue").fetchone()
    add(f"**{total} findings across {codes} issue codes.**\n")

    add("## Counts by severity\n")
    add("| Severity | Findings |")
    add("|---|---|")
    for r in conn.execute("SELECT severity, COUNT(*) n FROM data_issue GROUP BY 1 ORDER BY CASE severity WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END"):
        add(f"| {r['severity']} | {r['n']} |")

    add("\n## Every issue code, with a worked example\n")
    for r in conn.execute(
        """SELECT issue_code, severity, COUNT(*) n,
                  group_concat(DISTINCT source_file) files
             FROM data_issue GROUP BY issue_code, severity ORDER BY n DESC, issue_code"""
    ):
        ex = conn.execute(
            "SELECT source_file, source_row, field, raw_value, action, resolved_value "
            "FROM data_issue WHERE issue_code = ? LIMIT 1",
            (r["issue_code"],),
        ).fetchone()
        add(f"### `{r['issue_code']}` — {r['severity']}, {r['n']} finding(s)\n")
        add(f"- files: {r['files']}")
        add(f"- example: `{ex['source_file']}` row {ex['source_row']}, field `{ex['field']}`")
        add(f"- raw value: `{(ex['raw_value'] or '')[:120]}`")
        add(f"- action: {ex['action']}")
        if ex["resolved_value"]:
            add(f"- resolved to: `{ex['resolved_value'][:120]}`")
        add("")

    add("## Merge outcome\n")
    row = conn.execute(
        """SELECT COUNT(*) people,
                  SUM(in_source1+in_source2+in_source3=3) all3,
                  SUM(in_source1+in_source2+in_source3=2) two,
                  SUM(in_source1+in_source2+in_source3<=1) one
             FROM person"""
    ).fetchone()
    read = conn.execute("SELECT COUNT(*) FROM source_record").fetchone()[0]
    ing = conn.execute("SELECT COUNT(*) FROM source_record WHERE status='ingested'").fetchone()[0]
    add(f"- raw rows read: **{read}**, ingested: **{ing}**, skipped/rejected: **{read - ing}**")
    add(f"- unique people: **{row['people']}** ({row['all3']} in all three sources, "
        f"{row['two']} in two, {row['one']} in one)\n")

    add("| Match method | People |")
    add("|---|---|")
    for r in conn.execute("SELECT match_methods, COUNT(*) n FROM person GROUP BY 1 ORDER BY n DESC"):
        add(f"| `{r['match_methods']}` | {r['n']} |")

    add("\n## Queued for human review\n")
    revs = conn.execute("SELECT reason, candidates FROM match_review WHERE resolved = 0").fetchall()
    if not revs:
        add("_none_")
    for r in revs:
        add(f"- {r['reason']}")
        add(f"  ```json\n  {r['candidates']}\n  ```")

    OUT.write_text("\n".join(L) + "\n")
    conn.close()
    print(f"wrote {OUT.relative_to(ROOT)} ({total} findings)")


if __name__ == "__main__":
    main()
